name: "Nightly deb and rpm build (musl binaries + old glibc dylibs)"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 600
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
    - run: |
        sudo apt update
        sudo apt install -y apt-utils # provides apt-ftparchive XXX: move to nix
        sudo apt install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static # binfmt
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: ton
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix build .?submodules=1#packages.x86_64-linux.ton-oldglibc_staticbinaries --print-build-logs -o result-x86_64
    - run: |
        nix develop \
          --command bash -e -c '
            mkdir packages-out
            ./packages/deb.sh packages-out $PWD/packages/deb/ton $PWD/result-x86_64* amd64'
    - run: |
        nix develop \
          --command bash -e -c '
            ./packages/rpm.sh packages-out $PWD/packages/rpm/SPECS/ton.spec $PWD/result-x86_64* x86_64'

    - run: nix build .?submodules=1#packages.aarch64-linux.ton-musl --print-build-logs --system aarch64-linux -o result-aarch64 # XXX: dylib build
    - run: |
        nix develop \
          --command bash -e -c '
            ./packages/deb.sh packages-out $PWD/packages/deb/ton $PWD/result-aarch64* aarch64'
    - run: |
        nix develop \
          --command bash -e -c '
            ./packages/rpm.sh packages-out $PWD/packages/rpm/SPECS/ton.spec $PWD/result-aarch64* aarch64'

    - if: ${{ !env.ACT }}
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries
        path: result*

    - run: |
        nix develop \
          --command bash -e -c '
            cd packages-out/deb-install
            dpkg-scanpackages . > Packages
            apt-ftparchive release . > Release'
    - run: |
        gh release edit nightly-deb --target master
        gh release upload --clobber nightly-deb packages-out/deb-install/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # We can't rely on GH Releases for RPM because a RPM repo must have a repodata/ directory
    # and Releases don't support directories
    - run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.PACKAGES_REPO_KEY }}"
        git config --global user.name ghactions
        git config --global user.email actions@github.com
    - run: |
        nix develop \
          --command bash -e -c '
            cd packages-out/rpm-install
            createrepo_c .'
    - run: |
        git clone git@github.com:tonthemoon/ton-repo.git
        cp -r packages-out/rpm-install ton-repo/rpm
    - run: |
        cd ton-repo
        git rm -rf *
        git add .
        git commit --amend -m "Import nightly $(date -I)"
        git push -f
