name: "Nightly deb and rpm build (static glibc)"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: ton
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .?submodules=1#packages.x86_64-linux-static.ton --print-build-logs
    - run: |
        nix develop \
          --command bash -e -c '
            mkdir packages-out
            ./packages/deb.sh packages-out packages/deb/ton result'
    - run: |
        nix develop \
          --command bash -e -c '
            ./packages/rpm.sh packages-out $PWD/packages/rpm/SPECS/ton.spec $PWD/result'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-packages
        path: packages-out
