name: "Nightly deb and rpm build (musl binaries + old glibc dylibs)"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
    - run: |
        sudo apt update
        sudo apt install -y apt-utils # XXX: move to nix
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: ton
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .?submodules=1#packages.x86_64-linux.ton-oldglibc_staticbinaries --print-build-logs -o result-x86_64
    - run: |
        nix develop \
          --command bash -e -c '
            mkdir packages-out
            ./packages/deb.sh packages-out $PWD/packages/deb/ton $PWD/result-x86_64* amd64'
    - run: |
        nix develop \
          --command bash -e -c '
            ./packages/rpm.sh packages-out $PWD/packages/rpm/SPECS/ton.spec $PWD/result-x86_64* x86_64'
    - if: ${{ !env.ACT }}
      uses: actions/upload-artifact@master
      with:
        name: ton-packages
        path: packages-out/*-install
    - if: ${{ !env.ACT }}
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries
        path: result*
    - run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.PACKAGES_REPO_KEY }}"
        git config --global user.name ghactions
        git config --global user.email actions@github.com
    - run: |
        git clone git@github.com:tonthemoon/ton-repo.git
        cp -r packages-out/deb-install ton-repo/deb
        cp -r packages-out/rpm-install ton-repo/rpm
    - run: |
        nix develop \
          --command bash -e -c '
            cd ton-repo/deb
            dpkg-scanpackages . > Packages
            apt-ftparchive release . > Release'
    - run: |
        nix develop \
          --command bash -e -c '
            cd ton-repo/rpm
            createrepo_c .'
    - run: |
        cd ton-repo
        git add .
        git commit -m "Import nightly $(date -I)"
        git push
